version: "2"
services:
  tarabalam:
    extends:
      file: common.yml
      service: app
    restart: always
    depends_on:
      - mysql
      - redis
    command: ["-wait", "tcp://mysql:3306", "-wait", "tcp://redis:6379", "-timeout", "30s", "npm", "start" ]
    environment:
      - SERVICE_NAME=tarabalam

  cron:
    extends:
      file: common.yml
      service: app
    restart: always
    depends_on:
      - mysql
    command: ["-wait", "tcp://mysql:3306", "-timeout", "30s", "node", "cron.js"]
    environment:
      - SERVICE_IGNORE=true

  mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=tarabalam
      - MYSQL_USER=tarabalam
      - MYSQL_PASSWORD=tarabalam
      - MYSQL_ROOT_PASSWORD=tarabalam
      - SERVICE_IGNORE=true

  redis:
    image: redis
    restart: always
    environment:
      - SERVICE_IGNORE=true

  nginx:
    build: ./nginx
    image: tarabalam/nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    links:
      - tarabalam
      - consul
      - registrator
    environment:
      - SERVICE_IGNORE=true

  # Consul and registrator container
  consul:
    image: gliderlabs/consul-server
    restart: always
    command: "-server -bootstrap"
    environment:
      - SERVICE_8300_IGNORE=true
      - SERVICE_8301_IGNORE=true
      - SERVICE_8302_IGNORE=true
      - SERVICE_8400_IGNORE=true
      - SERVICE_8600_IGNORE=true
      - SERVICE_8500_NAME=consului

  registrator:
    image: gliderlabs/registrator
    restart: always
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    links:
      - consul
    command: ["-internal", "consul://consul:8500"]
